modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/MerchantPug/apugli/issues"
license = "MIT"

[[mods]]
modId = "apugli"
logoFile="apugli_icon.png"
version = "${version}"
displayName = "Apugli"
authors = "MerchantPug"
displayURL="https://github.com/MerchantPug/apugli"
description = '''
Pug's extension to Origins for data driven content.
'''

[[dependencies.apugli]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.apugli]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.apugli]]
modId = "architectury"
mandatory = true
versionRange = "[1.10.142,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.apugli]]
modId = "origins"
mandatory = true
versionRange = "[0.7.3.9,)"
ordering = "AFTER"
side = "BOTH"