modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "apugli"
version = "${version}"
displayName = "Apugli"
authors = "Pug"
description = '''
Pug's extension to Origins for powers.
'''
#logoFile = ""

[[dependencies.apugli]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.apugli]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.apugli]]
modId = "architectury"
mandatory = true
versionRange = "[1.10.140,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.apugli]]
modId = "origins"
mandatory = true
versionRange = "[0.7.3.9,)"
ordering = "AFTER"
side = "BOTH"