modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/MerchantPug/apugli/issues"
[[mods]]
modId="apugli"
version="${version}"
displayName="Apugli"
#updateJSONURL=""
displayURL="https://github.com/MerchantPug/apugli"
logoFile="pack.png"
authors="MerchantPug, LimonBlaze"
description="Pug's extension to A Power Library."

[[dependencies.apugli]]
    modId="forge"
    mandatory=true
    versionRange="[43.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apugli]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apugli]]
    modId="apoli"
    mandatory=true
    versionRange="[1.19.2-2.3.4.4,)"
    ordering="AFTER"
    side="BOTH"