name: Release
on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Upload releases
        run: ./gradlew build publish curseforge github modrinth --stacktrace
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}